"""initial schema

Revision ID: 4e423202c85f
Revises: 
Create Date: 2026-06-29 18:27:36.802076
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '4e423202c85f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner', sa.String(length=255), nullable=False),
    sa.Column('doc_type', sa.String(length=64), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('blob_ref', sa.String(length=1024), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_doc_type'), 'documents', ['doc_type'], unique=False)
    op.create_index(op.f('ix_documents_owner'), 'documents', ['owner'], unique=False)
    op.create_index(op.f('ix_documents_status'), 'documents', ['status'], unique=False)
    op.create_table('machine_snapshots',
    sa.Column('run_id', sa.String(length=256), nullable=False),
    sa.Column('machine_name', sa.String(length=128), nullable=False),
    sa.Column('current_state', sa.String(length=128), nullable=False),
    sa.Column('snapshot_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_index(op.f('ix_machine_snapshots_current_state'), 'machine_snapshots', ['current_state'], unique=False)
    op.create_table('validation_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('machine_id', sa.String(length=128), nullable=False),
    sa.Column('machine_version', sa.String(length=64), nullable=False),
    sa.Column('machine_hash', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('queued_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validation_runs_document_id'), 'validation_runs', ['document_id'], unique=False)
    op.create_index(op.f('ix_validation_runs_status'), 'validation_runs', ['status'], unique=False)
    op.create_table('validation_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('verdict', sa.String(length=16), nullable=False),
    sa.Column('final_state', sa.String(length=128), nullable=False),
    sa.Column('reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('extracted_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('machine_context', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['validation_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validation_results_run_id'), 'validation_results', ['run_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_validation_results_run_id'), table_name='validation_results')
    op.drop_table('validation_results')
    op.drop_index(op.f('ix_validation_runs_status'), table_name='validation_runs')
    op.drop_index(op.f('ix_validation_runs_document_id'), table_name='validation_runs')
    op.drop_table('validation_runs')
    op.drop_index(op.f('ix_machine_snapshots_current_state'), table_name='machine_snapshots')
    op.drop_table('machine_snapshots')
    op.drop_index(op.f('ix_documents_status'), table_name='documents')
    op.drop_index(op.f('ix_documents_owner'), table_name='documents')
    op.drop_index(op.f('ix_documents_doc_type'), table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
