const wrap: React.CSSProperties = { maxWidth: 760, margin: "0 auto", padding: 24, lineHeight: 1.6 };

export default function Tos() {
  return (
    <main style={wrap}>
      <h1>Terms of Service</h1>
      <p style={{ color: "#8b949e" }}>
        ORCA Validator is an experimental demo. By using it, you agree to the following.
      </p>

      <h2>Experimental, provided &ldquo;as is&rdquo;</h2>
      <p>
        The Service is provided <strong>&ldquo;AS IS&rdquo; and &ldquo;AS AVAILABLE&rdquo;</strong>,
        without warranties of any kind, express or implied. It is a demonstration, may be unreliable,
        and may change or be discontinued at any time without notice.
      </p>

      <h2 style={{ color: "#f85149" }}>Not legal advice</h2>
      <p>
        The verdict is produced by a formally-verified state machine that checks document{" "}
        <em>structure only</em>. The analysis and proposed revisions are generated by an AI model and
        may be inaccurate, incomplete, or wrong. <strong>None of the output is legal advice</strong>{" "}
        and must not be relied upon. Consult a qualified attorney before acting on anything here.
      </p>

      <h2>Your responsibilities</h2>
      <ul>
        <li>Only upload documents you have the right to upload and process.</li>
        <li>Do not upload confidential or sensitive data (see the <a href="/privacy" style={{ color: "#58a6ff" }}>Privacy Notice</a>).</li>
        <li>Do not abuse, overload, scrape, or attack the Service. Usage is rate-limited.</li>
      </ul>

      <h2>Limitation of liability</h2>
      <p>
        To the maximum extent permitted by law, the operators of this demo are not liable for any
        damages or losses arising from use of the Service or reliance on its output.
      </p>

      <p style={{ marginTop: 32 }}>
        <a href="/" style={{ color: "#58a6ff" }}>&larr; back to the app</a>
        {"  ·  "}
        <a href="/privacy" style={{ color: "#58a6ff" }}>Privacy Notice</a>
      </p>
    </main>
  );
}
